image: node:10.12.0-jessie
variables:
  GIT_STRATEGY: fetch
  Timeout: 10
stages:
  - install
  - test
  - deploy
install_job:
  stage: install
  script:
    - npm install
test_job:
  stage: test
  script:
    - npm run jest
job1:
  script: rspec
  coverage: './coverage/
  