image: node:10.12.0-jessie
variables:
  GIT_STRATEGY: fetch
  Timeout: 10
stages:
  - install
  - test
  - deploy
install_job:
  stage: install
  cache:
    paths:
      - node_modules
  script:
    - npm install
test_job:
  stage: test
  cache:
    paths:
      - node_modules
  script:
    - npm run jest
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
